# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'v4_24LCD.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


import time
import requests
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import sys

class Ui_MainWindow(QWidget):
    def __init__(self,parent=None):
        super(Ui_MainWindow, self).__init__(parent)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1174, 709)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formTitle = QtWidgets.QLabel(self.centralwidget)
        self.formTitle.setGeometry(QtCore.QRect(440, 10, 311, 51))
        self.formTitle.setText("")
        self.formTitle.setPixmap(QtGui.QPixmap("f2.jpg"))
        self.formTitle.setObjectName("formTitle")
        self.BGImg = QtWidgets.QLabel(self.centralwidget)
        self.BGImg.setGeometry(QtCore.QRect(0, 0, 1181, 701))
        self.BGImg.setText("")
        self.BGImg.setPixmap(QtGui.QPixmap("f1_1.jpg"))
        self.BGImg.setObjectName("BGImg")
        self.poolC1 = QtWidgets.QLabel(self.centralwidget)
        self.poolC1.setGeometry(QtCore.QRect(70, 110, 291, 501))
        self.poolC1.setText("")
        self.poolC1.setPixmap(QtGui.QPixmap("f3.jpg"))
        self.poolC1.setObjectName("poolC1")
        self.poolC2 = QtWidgets.QLabel(self.centralwidget)
        self.poolC2.setGeometry(QtCore.QRect(450, 110, 291, 501))
        self.poolC2.setText("")
        self.poolC2.setPixmap(QtGui.QPixmap("f4.jpg"))
        self.poolC2.setObjectName("poolC2")
        self.poolC3 = QtWidgets.QLabel(self.centralwidget)
        self.poolC3.setGeometry(QtCore.QRect(830, 110, 291, 501))
        self.poolC3.setText("")
        self.poolC3.setPixmap(QtGui.QPixmap("f5.jpg"))
        self.poolC3.setObjectName("poolC3")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(210, 120, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setAutoFillBackground(False)
        self.lcdNumber.setStyleSheet("color: rgb(170, 85, 0);\n"
"border-color: rgb(255, 255, 255);")
        self.lcdNumber.setLineWidth(0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setGeometry(QtCore.QRect(210, 180, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_2.setFont(font)
        self.lcdNumber_2.setAutoFillBackground(False)
        self.lcdNumber_2.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_2.setLineWidth(0)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_3.setGeometry(QtCore.QRect(210, 240, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_3.setFont(font)
        self.lcdNumber_3.setAutoFillBackground(False)
        self.lcdNumber_3.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_3.setLineWidth(0)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_4.setGeometry(QtCore.QRect(210, 300, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_4.setFont(font)
        self.lcdNumber_4.setAutoFillBackground(False)
        self.lcdNumber_4.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_4.setLineWidth(0)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.lcdNumber_5 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_5.setGeometry(QtCore.QRect(210, 370, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_5.setFont(font)
        self.lcdNumber_5.setAutoFillBackground(False)
        self.lcdNumber_5.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_5.setLineWidth(0)
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.lcdNumber_6 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_6.setGeometry(QtCore.QRect(210, 430, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_6.setFont(font)
        self.lcdNumber_6.setAutoFillBackground(False)
        self.lcdNumber_6.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_6.setLineWidth(0)
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.lcdNumber_7 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_7.setGeometry(QtCore.QRect(210, 490, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_7.setFont(font)
        self.lcdNumber_7.setAutoFillBackground(False)
        self.lcdNumber_7.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_7.setLineWidth(0)
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.lcdNumber_8 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_8.setGeometry(QtCore.QRect(210, 550, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_8.setFont(font)
        self.lcdNumber_8.setAutoFillBackground(False)
        self.lcdNumber_8.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_8.setLineWidth(0)
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.lcdNumber_9 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_9.setGeometry(QtCore.QRect(590, 120, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_9.setFont(font)
        self.lcdNumber_9.setAutoFillBackground(False)
        self.lcdNumber_9.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_9.setLineWidth(0)
        self.lcdNumber_9.setObjectName("lcdNumber_9")
        self.lcdNumber_10 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_10.setGeometry(QtCore.QRect(590, 180, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_10.setFont(font)
        self.lcdNumber_10.setAutoFillBackground(False)
        self.lcdNumber_10.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_10.setLineWidth(0)
        self.lcdNumber_10.setObjectName("lcdNumber_10")
        self.lcdNumber_11 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_11.setGeometry(QtCore.QRect(590, 240, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_11.setFont(font)
        self.lcdNumber_11.setAutoFillBackground(False)
        self.lcdNumber_11.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_11.setLineWidth(0)
        self.lcdNumber_11.setObjectName("lcdNumber_11")
        self.lcdNumber_12 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_12.setGeometry(QtCore.QRect(590, 300, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_12.setFont(font)
        self.lcdNumber_12.setAutoFillBackground(False)
        self.lcdNumber_12.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_12.setLineWidth(0)
        self.lcdNumber_12.setObjectName("lcdNumber_12")
        self.lcdNumber_13 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_13.setGeometry(QtCore.QRect(590, 370, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_13.setFont(font)
        self.lcdNumber_13.setAutoFillBackground(False)
        self.lcdNumber_13.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_13.setLineWidth(0)
        self.lcdNumber_13.setObjectName("lcdNumber_13")
        self.lcdNumber_14 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_14.setGeometry(QtCore.QRect(590, 430, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_14.setFont(font)
        self.lcdNumber_14.setAutoFillBackground(False)
        self.lcdNumber_14.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_14.setLineWidth(0)
        self.lcdNumber_14.setObjectName("lcdNumber_14")
        self.lcdNumber_15 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_15.setGeometry(QtCore.QRect(590, 490, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_15.setFont(font)
        self.lcdNumber_15.setAutoFillBackground(False)
        self.lcdNumber_15.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_15.setLineWidth(0)
        self.lcdNumber_15.setObjectName("lcdNumber_15")
        self.lcdNumber_16 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_16.setGeometry(QtCore.QRect(590, 550, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_16.setFont(font)
        self.lcdNumber_16.setAutoFillBackground(False)
        self.lcdNumber_16.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_16.setLineWidth(0)
        self.lcdNumber_16.setObjectName("lcdNumber_16")
        self.lcdNumber_17 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_17.setGeometry(QtCore.QRect(980, 120, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_17.setFont(font)
        self.lcdNumber_17.setAutoFillBackground(False)
        self.lcdNumber_17.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_17.setLineWidth(0)
        self.lcdNumber_17.setObjectName("lcdNumber_17")
        self.lcdNumber_18 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_18.setGeometry(QtCore.QRect(980, 180, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_18.setFont(font)
        self.lcdNumber_18.setAutoFillBackground(False)
        self.lcdNumber_18.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_18.setLineWidth(0)
        self.lcdNumber_18.setObjectName("lcdNumber_18")
        self.lcdNumber_19 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_19.setGeometry(QtCore.QRect(980, 240, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_19.setFont(font)
        self.lcdNumber_19.setAutoFillBackground(False)
        self.lcdNumber_19.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_19.setLineWidth(0)
        self.lcdNumber_19.setObjectName("lcdNumber_19")
        self.lcdNumber_20 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_20.setGeometry(QtCore.QRect(980, 300, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_20.setFont(font)
        self.lcdNumber_20.setAutoFillBackground(False)
        self.lcdNumber_20.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_20.setLineWidth(0)
        self.lcdNumber_20.setObjectName("lcdNumber_20")
        self.lcdNumber_21 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_21.setGeometry(QtCore.QRect(980, 370, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_21.setFont(font)
        self.lcdNumber_21.setAutoFillBackground(False)
        self.lcdNumber_21.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_21.setLineWidth(0)
        self.lcdNumber_21.setObjectName("lcdNumber_21")
        self.lcdNumber_22 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_22.setGeometry(QtCore.QRect(980, 430, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_22.setFont(font)
        self.lcdNumber_22.setAutoFillBackground(False)
        self.lcdNumber_22.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_22.setLineWidth(0)
        self.lcdNumber_22.setObjectName("lcdNumber_22")
        self.lcdNumber_23 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_23.setGeometry(QtCore.QRect(980, 490, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_23.setFont(font)
        self.lcdNumber_23.setAutoFillBackground(False)
        self.lcdNumber_23.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_23.setLineWidth(0)
        self.lcdNumber_23.setObjectName("lcdNumber_23")
        self.lcdNumber_24 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_24.setGeometry(QtCore.QRect(980, 550, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_24.setFont(font)
        self.lcdNumber_24.setAutoFillBackground(False)
        self.lcdNumber_24.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_24.setLineWidth(0)
        self.lcdNumber_24.setObjectName("lcdNumber_24")
        self.BGImg.raise_()
        self.formTitle.raise_()
        self.poolC1.raise_()
        self.poolC2.raise_()
        self.poolC3.raise_()
        self.lcdNumber.raise_()
        self.lcdNumber_2.raise_()
        self.lcdNumber_3.raise_()
        self.lcdNumber_4.raise_()
        self.lcdNumber_5.raise_()
        self.lcdNumber_6.raise_()
        self.lcdNumber_7.raise_()
        self.lcdNumber_8.raise_()
        self.lcdNumber_9.raise_()
        self.lcdNumber_10.raise_()
        self.lcdNumber_11.raise_()
        self.lcdNumber_12.raise_()
        self.lcdNumber_13.raise_()
        self.lcdNumber_14.raise_()
        self.lcdNumber_15.raise_()
        self.lcdNumber_16.raise_()
        self.lcdNumber_17.raise_()
        self.lcdNumber_18.raise_()
        self.lcdNumber_19.raise_()
        self.lcdNumber_20.raise_()
        self.lcdNumber_21.raise_()
        self.lcdNumber_22.raise_()
        self.lcdNumber_23.raise_()
        self.lcdNumber_24.raise_()

        '''usr code'''
        self.timer=QTimer()
        self.timer.setInterval(1000)
        self.timer.start()
        #self.cnter=1
        self.read_data_thingspeak()
        self.timer.timeout.connect(self.updateLCD)
        '''usr code'''

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

    def updateLCD(self): #display the variable 'event' to the display
        self.lcdNumber.display(self.t[-1])
        #self.cnter+=1
        self.read_data_thingspeak()

    def read_data_thingspeak(self):
        URL='https://api.thingspeak.com/channels/983197/fields/1.json?api_key=26ZX2F1R5YCUA83A&results=20'
        print(URL)
        get_data=requests.get(URL).json()
        feild_1=get_data['feeds']
        #print(feild_1)
        self.t=[]
        for x in feild_1:
            #print(x['field1'])
            self.t.append(x['field1'])
        #return self.t[-1]

''' user code '''
if __name__ == '__main__':
    #tt=read_data_thingspeak()
    app=QtWidgets.QApplication(sys.argv)
    MainWindow=QtWidgets.QMainWindow()
    ui=Ui_MainWindow()
    ui.setupUi(MainWindow)
#    ui.updateLCD(tt[-1])
    #tt[-1]+='1'
    MainWindow.show()
    sys.exit(app.exec_())
''' user code '''
