# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'v7_24LCDButtonExcelFinal.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


import time
import requests
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import sys
import matplotlib.pyplot as plt
import pandas as pd
#from matplotlib.pyplot import figure

class Ui_MainWindow(QWidget):
    def __init__(self,parent=None):
        super(Ui_MainWindow, self).__init__(parent)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(606, 330)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(130, 70, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setAutoFillBackground(False)
        self.lcdNumber.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-color: rgb(255, 255, 255);")
        self.lcdNumber.setLineWidth(0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setGeometry(QtCore.QRect(130, 100, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_2.setFont(font)
        self.lcdNumber_2.setAutoFillBackground(False)
        self.lcdNumber_2.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_2.setLineWidth(0)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_3.setGeometry(QtCore.QRect(130, 130, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_3.setFont(font)
        self.lcdNumber_3.setAutoFillBackground(False)
        self.lcdNumber_3.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_3.setLineWidth(0)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_4.setGeometry(QtCore.QRect(130, 160, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_4.setFont(font)
        self.lcdNumber_4.setAutoFillBackground(False)
        self.lcdNumber_4.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_4.setLineWidth(0)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.lcdNumber_5 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_5.setGeometry(QtCore.QRect(130, 190, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_5.setFont(font)
        self.lcdNumber_5.setAutoFillBackground(False)
        self.lcdNumber_5.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_5.setLineWidth(0)
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.lcdNumber_6 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_6.setGeometry(QtCore.QRect(130, 220, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_6.setFont(font)
        self.lcdNumber_6.setAutoFillBackground(False)
        self.lcdNumber_6.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_6.setLineWidth(0)
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.lcdNumber_7 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_7.setGeometry(QtCore.QRect(130, 250, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_7.setFont(font)
        self.lcdNumber_7.setAutoFillBackground(False)
        self.lcdNumber_7.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_7.setLineWidth(0)
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.lcdNumber_8 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_8.setGeometry(QtCore.QRect(130, 280, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_8.setFont(font)
        self.lcdNumber_8.setAutoFillBackground(False)
        self.lcdNumber_8.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_8.setLineWidth(0)
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.lcdNumber_9 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_9.setGeometry(QtCore.QRect(320, 70, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_9.setFont(font)
        self.lcdNumber_9.setAutoFillBackground(False)
        self.lcdNumber_9.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_9.setLineWidth(0)
        self.lcdNumber_9.setObjectName("lcdNumber_9")
        self.lcdNumber_10 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_10.setGeometry(QtCore.QRect(320, 100, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_10.setFont(font)
        self.lcdNumber_10.setAutoFillBackground(False)
        self.lcdNumber_10.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_10.setLineWidth(0)
        self.lcdNumber_10.setObjectName("lcdNumber_10")
        self.lcdNumber_11 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_11.setGeometry(QtCore.QRect(320, 130, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_11.setFont(font)
        self.lcdNumber_11.setAutoFillBackground(False)
        self.lcdNumber_11.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_11.setLineWidth(0)
        self.lcdNumber_11.setObjectName("lcdNumber_11")
        self.lcdNumber_12 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_12.setGeometry(QtCore.QRect(320, 160, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_12.setFont(font)
        self.lcdNumber_12.setAutoFillBackground(False)
        self.lcdNumber_12.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_12.setLineWidth(0)
        self.lcdNumber_12.setObjectName("lcdNumber_12")
        self.lcdNumber_13 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_13.setGeometry(QtCore.QRect(320, 190, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_13.setFont(font)
        self.lcdNumber_13.setAutoFillBackground(False)
        self.lcdNumber_13.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_13.setLineWidth(0)
        self.lcdNumber_13.setObjectName("lcdNumber_13")
        self.lcdNumber_14 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_14.setGeometry(QtCore.QRect(320, 220, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_14.setFont(font)
        self.lcdNumber_14.setAutoFillBackground(False)
        self.lcdNumber_14.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_14.setLineWidth(0)
        self.lcdNumber_14.setObjectName("lcdNumber_14")
        self.lcdNumber_15 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_15.setGeometry(QtCore.QRect(320, 250, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_15.setFont(font)
        self.lcdNumber_15.setAutoFillBackground(False)
        self.lcdNumber_15.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_15.setLineWidth(0)
        self.lcdNumber_15.setObjectName("lcdNumber_15")
        self.lcdNumber_16 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_16.setGeometry(QtCore.QRect(320, 280, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_16.setFont(font)
        self.lcdNumber_16.setAutoFillBackground(False)
        self.lcdNumber_16.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_16.setLineWidth(0)
        self.lcdNumber_16.setObjectName("lcdNumber_16")
        self.lcdNumber_17 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_17.setGeometry(QtCore.QRect(520, 70, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_17.setFont(font)
        self.lcdNumber_17.setAutoFillBackground(False)
        self.lcdNumber_17.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_17.setLineWidth(0)
        self.lcdNumber_17.setObjectName("lcdNumber_17")
        self.lcdNumber_18 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_18.setGeometry(QtCore.QRect(520, 100, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_18.setFont(font)
        self.lcdNumber_18.setAutoFillBackground(False)
        self.lcdNumber_18.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_18.setLineWidth(0)
        self.lcdNumber_18.setObjectName("lcdNumber_18")
        self.lcdNumber_19 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_19.setGeometry(QtCore.QRect(520, 130, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_19.setFont(font)
        self.lcdNumber_19.setAutoFillBackground(False)
        self.lcdNumber_19.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_19.setLineWidth(0)
        self.lcdNumber_19.setObjectName("lcdNumber_19")
        self.lcdNumber_20 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_20.setGeometry(QtCore.QRect(520, 160, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_20.setFont(font)
        self.lcdNumber_20.setAutoFillBackground(False)
        self.lcdNumber_20.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_20.setLineWidth(0)
        self.lcdNumber_20.setObjectName("lcdNumber_20")
        self.lcdNumber_21 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_21.setGeometry(QtCore.QRect(520, 190, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_21.setFont(font)
        self.lcdNumber_21.setAutoFillBackground(False)
        self.lcdNumber_21.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_21.setLineWidth(0)
        self.lcdNumber_21.setObjectName("lcdNumber_21")
        self.lcdNumber_22 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_22.setGeometry(QtCore.QRect(520, 220, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_22.setFont(font)
        self.lcdNumber_22.setAutoFillBackground(False)
        self.lcdNumber_22.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_22.setLineWidth(0)
        self.lcdNumber_22.setObjectName("lcdNumber_22")
        self.lcdNumber_23 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_23.setGeometry(QtCore.QRect(520, 250, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_23.setFont(font)
        self.lcdNumber_23.setAutoFillBackground(False)
        self.lcdNumber_23.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_23.setLineWidth(0)
        self.lcdNumber_23.setObjectName("lcdNumber_23")
        self.lcdNumber_24 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_24.setGeometry(QtCore.QRect(520, 280, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lcdNumber_24.setFont(font)
        self.lcdNumber_24.setAutoFillBackground(False)
        self.lcdNumber_24.setStyleSheet("color: rgb(170, 85, 0);")
        self.lcdNumber_24.setLineWidth(0)
        self.lcdNumber_24.setObjectName("lcdNumber_24")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 70, 21, 21))
        self.pushButton.setStyleSheet("")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")

        '''usr code'''
        self.pushButton.clicked.connect(self.plotTheData)
        '''usr code'''

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 100, 21, 21))
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 130, 21, 21))
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 160, 21, 21))
        self.pushButton_4.setStyleSheet("")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 190, 21, 21))
        self.pushButton_5.setStyleSheet("")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 220, 21, 21))
        self.pushButton_6.setStyleSheet("")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(30, 250, 21, 21))
        self.pushButton_7.setStyleSheet("")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(30, 280, 21, 21))
        self.pushButton_8.setStyleSheet("")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(220, 70, 21, 21))
        self.pushButton_9.setStyleSheet("")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(220, 100, 21, 21))
        self.pushButton_10.setStyleSheet("")
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(220, 130, 21, 21))
        self.pushButton_11.setStyleSheet("")
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(220, 160, 21, 21))
        self.pushButton_12.setStyleSheet("")
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(220, 190, 21, 21))
        self.pushButton_13.setStyleSheet("")
        self.pushButton_13.setText("")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(220, 220, 21, 21))
        self.pushButton_14.setStyleSheet("")
        self.pushButton_14.setText("")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(220, 250, 21, 21))
        self.pushButton_15.setStyleSheet("")
        self.pushButton_15.setText("")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(220, 280, 21, 21))
        self.pushButton_16.setStyleSheet("")
        self.pushButton_16.setText("")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(420, 70, 21, 21))
        self.pushButton_17.setStyleSheet("")
        self.pushButton_17.setText("")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(420, 100, 21, 21))
        self.pushButton_18.setStyleSheet("")
        self.pushButton_18.setText("")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(420, 130, 21, 21))
        self.pushButton_19.setStyleSheet("")
        self.pushButton_19.setText("")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(420, 160, 21, 21))
        self.pushButton_20.setStyleSheet("")
        self.pushButton_20.setText("")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setGeometry(QtCore.QRect(420, 190, 21, 21))
        self.pushButton_21.setStyleSheet("")
        self.pushButton_21.setText("")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_22.setGeometry(QtCore.QRect(420, 220, 21, 21))
        self.pushButton_22.setStyleSheet("")
        self.pushButton_22.setText("")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setGeometry(QtCore.QRect(420, 250, 21, 21))
        self.pushButton_23.setStyleSheet("")
        self.pushButton_23.setText("")
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_24.setGeometry(QtCore.QRect(420, 280, 21, 21))
        self.pushButton_24.setStyleSheet("")
        self.pushButton_24.setText("")
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_ex1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ex1.setGeometry(QtCore.QRect(60, 70, 21, 21))
        self.pushButton_ex1.setText("")
        self.pushButton_ex1.setObjectName("pushButton_ex1")

        '''usr code'''
        self.pushButton_ex1.clicked.connect(self.exportData)
        '''usr code'''

        self.pushButton_ex2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ex2.setGeometry(QtCore.QRect(60, 100, 21, 21))
        self.pushButton_ex2.setText("")
        self.pushButton_ex2.setObjectName("pushButton_ex2")
        self.pushButton_ex3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ex3.setGeometry(QtCore.QRect(60, 130, 21, 21))
        self.pushButton_ex3.setText("")
        self.pushButton_ex3.setObjectName("pushButton_ex3")
        self.pushButton_ex4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ex4.setGeometry(QtCore.QRect(60, 160, 21, 21))
        self.pushButton_ex4.setText("")
        self.pushButton_ex4.setObjectName("pushButton_ex4")
        self.pushButton_ex5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ex5.setGeometry(QtCore.QRect(60, 190, 21, 21))
        self.pushButton_ex5.setText("")
        self.pushButton_ex5.setObjectName("pushButton_ex5")
        self.pushButton_ex6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ex6.setGeometry(QtCore.QRect(60, 220, 21, 21))
        self.pushButton_ex6.setText("")
        self.pushButton_ex6.setObjectName("pushButton_ex6")
        self.pushButton_ex7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ex7.setGeometry(QtCore.QRect(60, 250, 21, 21))
        self.pushButton_ex7.setText("")
        self.pushButton_ex7.setObjectName("pushButton_ex7")
        self.pushButton_ex8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ex8.setGeometry(QtCore.QRect(60, 280, 21, 21))
        self.pushButton_ex8.setText("")
        self.pushButton_ex8.setObjectName("pushButton_ex8")
        self.pushButton_ex9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ex9.setGeometry(QtCore.QRect(250, 70, 21, 21))
        self.pushButton_ex9.setText("")
        self.pushButton_ex9.setObjectName("pushButton_ex9")
        self.pushButton_ex10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ex10.setGeometry(QtCore.QRect(250, 100, 21, 21))
        self.pushButton_ex10.setText("")
        self.pushButton_ex10.setObjectName("pushButton_ex10")
        self.pushButton_ex11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ex11.setGeometry(QtCore.QRect(250, 130, 21, 21))
        self.pushButton_ex11.setText("")
        self.pushButton_ex11.setObjectName("pushButton_ex11")
        self.pushButton_ex12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ex12.setGeometry(QtCore.QRect(250, 160, 21, 21))
        self.pushButton_ex12.setText("")
        self.pushButton_ex12.setObjectName("pushButton_ex12")
        self.pushButton_ex13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ex13.setGeometry(QtCore.QRect(250, 190, 21, 21))
        self.pushButton_ex13.setText("")
        self.pushButton_ex13.setObjectName("pushButton_ex13")
        self.pushButton_ex14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ex14.setGeometry(QtCore.QRect(250, 220, 21, 21))
        self.pushButton_ex14.setText("")
        self.pushButton_ex14.setObjectName("pushButton_ex14")
        self.pushButton_ex15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ex15.setGeometry(QtCore.QRect(250, 250, 21, 21))
        self.pushButton_ex15.setText("")
        self.pushButton_ex15.setObjectName("pushButton_ex15")
        self.pushButton_ex16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ex16.setGeometry(QtCore.QRect(250, 280, 21, 21))
        self.pushButton_ex16.setText("")
        self.pushButton_ex16.setObjectName("pushButton_ex16")
        self.pushButton_ex17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ex17.setGeometry(QtCore.QRect(450, 70, 21, 21))
        self.pushButton_ex17.setText("")
        self.pushButton_ex17.setObjectName("pushButton_ex17")
        self.pushButton_ex18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ex18.setGeometry(QtCore.QRect(450, 100, 21, 21))
        self.pushButton_ex18.setText("")
        self.pushButton_ex18.setObjectName("pushButton_ex18")
        self.pushButton_ex19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ex19.setGeometry(QtCore.QRect(450, 130, 21, 21))
        self.pushButton_ex19.setText("")
        self.pushButton_ex19.setObjectName("pushButton_ex19")
        self.pushButton_ex20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ex20.setGeometry(QtCore.QRect(450, 160, 21, 21))
        self.pushButton_ex20.setText("")
        self.pushButton_ex20.setObjectName("pushButton_ex20")
        self.pushButton_ex21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ex21.setGeometry(QtCore.QRect(450, 190, 21, 21))
        self.pushButton_ex21.setText("")
        self.pushButton_ex21.setObjectName("pushButton_ex21")
        self.pushButton_ex22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ex22.setGeometry(QtCore.QRect(450, 220, 21, 21))
        self.pushButton_ex22.setText("")
        self.pushButton_ex22.setObjectName("pushButton_ex22")
        self.pushButton_ex23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ex23.setGeometry(QtCore.QRect(450, 250, 21, 21))
        self.pushButton_ex23.setText("")
        self.pushButton_ex23.setObjectName("pushButton_ex23")
        self.pushButton_ex24 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ex24.setGeometry(QtCore.QRect(450, 280, 21, 21))
        self.pushButton_ex24.setText("")
        self.pushButton_ex24.setObjectName("pushButton_ex24")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 601, 321))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("f6.jpg"))
        self.label.setObjectName("label")
        self.label.raise_()
        self.pushButton_7.raise_()
        self.lcdNumber_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_4.raise_()
        self.pushButton_ex3.raise_()
        self.pushButton_2.raise_()
        self.lcdNumber_6.raise_()
        self.pushButton_8.raise_()
        self.pushButton_ex1.raise_()
        self.pushButton_ex7.raise_()
        self.pushButton.raise_()
        self.pushButton_5.raise_()
        self.lcdNumber.raise_()
        self.pushButton_ex8.raise_()
        self.lcdNumber_4.raise_()
        self.pushButton_ex5.raise_()
        self.lcdNumber_2.raise_()
        self.lcdNumber_3.raise_()
        self.pushButton_ex6.raise_()
        self.lcdNumber_8.raise_()
        self.pushButton_ex2.raise_()
        self.lcdNumber_7.raise_()
        self.pushButton_3.raise_()
        self.pushButton_ex4.raise_()
        self.pushButton_15.raise_()
        self.lcdNumber_13.raise_()
        self.pushButton_ex14.raise_()
        self.pushButton_11.raise_()
        self.pushButton_12.raise_()
        self.pushButton_13.raise_()
        self.pushButton_9.raise_()
        self.lcdNumber_16.raise_()
        self.lcdNumber_10.raise_()
        self.pushButton_ex13.raise_()
        self.pushButton_10.raise_()
        self.pushButton_16.raise_()
        self.lcdNumber_11.raise_()
        self.pushButton_ex10.raise_()
        self.pushButton_ex11.raise_()
        self.lcdNumber_12.raise_()
        self.lcdNumber_14.raise_()
        self.pushButton_14.raise_()
        self.pushButton_ex16.raise_()
        self.pushButton_ex12.raise_()
        self.pushButton_ex15.raise_()
        self.pushButton_ex9.raise_()
        self.lcdNumber_9.raise_()
        self.lcdNumber_15.raise_()
        self.lcdNumber_22.raise_()
        self.pushButton_22.raise_()
        self.pushButton_ex20.raise_()
        self.pushButton_20.raise_()
        self.pushButton_ex23.raise_()
        self.lcdNumber_21.raise_()
        self.lcdNumber_17.raise_()
        self.pushButton_19.raise_()
        self.pushButton_24.raise_()
        self.pushButton_18.raise_()
        self.pushButton_ex18.raise_()
        self.pushButton_17.raise_()
        self.pushButton_ex21.raise_()
        self.lcdNumber_20.raise_()
        self.pushButton_ex22.raise_()
        self.lcdNumber_18.raise_()
        self.lcdNumber_19.raise_()
        self.lcdNumber_23.raise_()
        self.lcdNumber_24.raise_()
        self.pushButton_ex17.raise_()
        self.pushButton_ex24.raise_()
        self.pushButton_23.raise_()
        self.pushButton_ex19.raise_()
        self.pushButton_21.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

        '''usr code'''
        self.timer=QTimer()
        self.timer.setInterval(1000)
        self.timer.start()
        #self.cnter=1
        self.read_data_thingspeak()
        self.timer.timeout.connect(self.updateLCD)
        '''usr code'''

        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

    def updateLCD(self): #display the variable 'event' to the display
        self.lcdNumber.display(self.t[-1])
        #self.cnter+=1
        self.read_data_thingspeak()

    def read_data_thingspeak(self):
        URL='https://api.thingspeak.com/channels/983197/fields/1.json?api_key=26ZX2F1R5YCUA83A&timezone=America%2FDenver'#use & to separate multiple requests.timezone has been added to it.If No. of results are not specified, it reads anything <=100 data entries.
        #URL_2='https://api.thingspeak.com/channels/983197/fields/1.json?api_key=26ZX2F1R5YCUA83A&results=8000&timezone=America%2FDenver'#read 8000 data entries, about 3 days 
#        URL='https://api.thingspeak.com/channels/983197/fields/1.json?api_key=26ZX2F1R5YCUA83A&timezone=America%2FDenver'#if you do not specify the '&results=xx' it will read all the data since a few days ago (seems like it is 8 days)  
        get_data=requests.get(URL).json()
        feild_1=get_data['feeds']
        #print(feild_1)
        self.t=[] #all the temp points
        self.tm=[] #all the time points
        for x in feild_1:
            #print(x['field1'])
            self.t.append(x['field1'])
            self.tm.append(x['created_at'])
        self.newselftm=[]#only shows the date and the time
        for tm in self.tm:
            self.newselftm.append(tm[:19])

    def plotTheData(self):
        fig=plt.figure(figsize=(12,10))
        plt.title("Temperature in Fahrenheit (in the past 20 min)",fontsize=20)
        #plt.xlabel("Time")
        plt.ylabel("Temperature",fontsize=20)
        halftm=len(self.newselftm)//2
        halft=len(self.t)//2
        for i in range(0,len(self.t)):# convert string data in the list to a int list
            self.t[i]=int(self.t[i])
        ax=plt.subplot(1,1,1)
        plt.ylim(0,250)#temp display range
        ax.scatter(self.newselftm[halftm:-1], self.t[halft:-1])
        #print(self.t)
        plt.setp(ax.get_xticklabels(),rotation=30,ha="right")
        for label in ax.get_xticklabels()[::2]:
            label.set_visible(False)
        mng = plt.get_current_fig_manager()
        mng.window.state('zoomed')
        plt.show()

    def exportData(self): # export 8000 data points to excel
        URL_2='https://api.thingspeak.com/channels/983197/fields/1.json?api_key=26ZX2F1R5YCUA83A&results=8000&timezone=America%2FDenver'#read 8000 data entries, about 3 days 
        get_data_ex=requests.get(URL_2).json()
        feild_1_ex=get_data_ex['feeds']
        self.t_ex=[] #all the temp points
        self.tm_ex=[] #all the time points
        for x_ex in feild_1_ex:
            self.t_ex.append(x_ex['field1'])
            self.tm_ex.append(x_ex['created_at'])
        self.newselftm_ex=[]#only shows the date and the time
        for tm_ex in self.tm_ex:
            self.newselftm_ex.append(tm_ex[:19])
        for i_ex in range(0,len(self.t_ex)):# convert string data in the list to a int list
            self.t_ex[i_ex]=int(self.t_ex[i_ex])
        df_ex=pd.DataFrame({'Time':self.tm_ex, 'Temperature':self.t_ex})
        writer_ex=pd.ExcelWriter('tempData.xlsx', engine='xlsxwriter')
        df_ex.to_excel(writer_ex, sheet_name='Temperature Data')
        writer_ex.save()





''' user code '''
if __name__ == '__main__':
    #tt=read_data_thingspeak()
    app=QtWidgets.QApplication(sys.argv)
    MainWindow=QtWidgets.QMainWindow()
    ui=Ui_MainWindow()
    ui.setupUi(MainWindow)
#    ui.updateLCD(tt[-1])
    #tt[-1]+='1'
    MainWindow.show() # show the GUI
    #ui.plotTheData() # plot the most recent 100 data points
    sys.exit(app.exec_())

